openctf:
  build: nginx
  links:
    - api
  ports:
    - "6001:80"
  volumes:
    - ./nginx/web:/srv/http/ctf

api:
  build: api
  env_file: .env
  links:
    - db
  expose:
    - 8000
  volumes:
    - ./api:/openctf
  entrypoint: ./wait-for-it.sh db

db:
  build: mysql
  env_file: .env
  expose:
    - 3306