"""empty message

Revision ID: 7f82413e5370
Revises: None
Create Date: 2016-07-15 12:07:32.761484

"""

# revision identifiers, used by Alembic.
revision = '7f82413e5370'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config')
    op.drop_table('tickets')
    op.drop_table('solves')
    op.drop_table('problems')
    op.drop_table('ticket_replies')
    op.drop_table('team_invitations')
    op.drop_table('programming_submissions')
    op.drop_table('teams')
    op.drop_table('files')
    op.drop_table('login_tokens')
    op.drop_table('activity')
    op.drop_table('pages')
    op.drop_table('users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('tid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('username_lower', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('utype', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('registertime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('reset_token', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('otp_secret', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('otp_confirmed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('email_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('email_token', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('pages',
    sa.Column('pgid', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('pvid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('pgid'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('activity',
    sa.Column('uaid', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('pid', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('uaid'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('login_tokens',
    sa.Column('sid', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('username', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('issued', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('expiry', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ua', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('ip', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('sid'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('files',
    sa.Column('fid', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('pid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('location', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('fid'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('teams',
    sa.Column('tid', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('teamname', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('teamname_lower', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('school', mysql.TEXT(), nullable=True),
    sa.Column('owner', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('observer', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('finalized', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('tid'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('programming_submissions',
    sa.Column('psid', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('pid', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('tid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('date', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('log', mysql.TEXT(), nullable=True),
    sa.Column('submission_path', mysql.TEXT(), nullable=True),
    sa.Column('number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('duration', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('psid'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('team_invitations',
    sa.Column('rid', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('rtype', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('frid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('toid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('date', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('rid'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('ticket_replies',
    sa.Column('trid', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('htid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('date', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('author', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('trid'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('problems',
    sa.Column('pid', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('hint', mysql.TEXT(), nullable=True),
    sa.Column('grader', mysql.TEXT(), nullable=True),
    sa.Column('autogen', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('bonus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('threshold', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('weightmap', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('pid'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('solves',
    sa.Column('sid', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('pid', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('tid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('date', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('correct', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('flag', mysql.TEXT(), nullable=True),
    sa.Column('bonus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('sid'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('tickets',
    sa.Column('htid', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('opened', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('author', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('title', mysql.TEXT(), nullable=True),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('htid'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('config',
    sa.Column('cfid', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('key', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('value', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('cfid'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
